import { SPECIES_SLUGS } from '@/lib/species-data'
import type { SpeciesHuntingSpecs, SpeciesSlug } from '@/lib/species-power-types'

export type { SpeciesHuntingSpecs, SpeciesSlug, SpeciesPowerDeepDive } from '@/lib/species-power-types'
export { getSpeciesPowerDeepDive, SPECIES_POWER_DEEP_DIVE } from '@/lib/species-power-deep-dive-content'

/** Quick-fact rows aligned with MIWESU animal_knowledge briefs, verify measurer / PH minima at booking. */
export const SPECIES_HUNTING_SPECS: Record<SpeciesSlug, SpeciesHuntingSpecs> = {
  'greater-kudu': {
    heroImage: '/images/greater-kudu_card.png', rowlandWardMinimum: 'Min. 53⅞″ measured along outside spiral (Rowland Ward)', averageTrophy: 'Mature bulls often 54–58″ class; exceptional 60″+; verify horn mass and tip wear with PH', recommendedCaliber: '.300 Win Mag · .30-06 Springfield · 7mm Rem Mag (premium bullets)', optimalSeason: 'Apr–Jun rut peak · May–Sep dry bush ideal for glassing', heroEyebrow: 'Spiral horn · Grey Ghost · Thicket edge', sciMinimum:
      'SCI spiral-horned antelope scoring combines length and circumference, confirm category tables for current rifle/bow minima with your outfitter.', bulletConstruction:
      'Bonded or partition .30-cal 165–180 gr, quality monolithic (TSX-class) if bone is likely; avoid fragile cup-and-core through heavy scrub.', liveWeight: 'Bulls typically ~190–270 kg mature; cows ~120–210 kg; exceptional bulls heavier on high-plane nutrition.', diet: 'Specialised browser: Vachellia/Senegalia, Combretum, sickle bush, pods and fruit; minimal grass except flush.', }, wildebeest: {
    heroImage: '/images/blue-wildebeest_card.png', rowlandWardMinimum: 'Min. 28½″ horn width (Rowland Ward methodology)', averageTrophy: 'Bulls commonly 29–31″ width; evaluate boss knurling, forehead mask, and body mass', recommendedCaliber: '.338 Win Mag · .300 Win Mag · .375 H&H (premium controlled expansion)', optimalSeason: 'Feb–Apr rut intensity · May–Oct visibility on short grass', heroEyebrow: 'Blue wildebeest · Concentrate grazer', sciMinimum: 'SCI blue wildebeest entry uses composite horn measurement, request latest SCI manual thresholds before export prep.', bulletConstruction:
      'Heavy-for-calibre bonded, A-Frame-class, or monolithic solids through shoulder potential; light deer bullets risk shallow wounds on boss hits.', liveWeight: 'Mature bulls ~250–290 kg typical; cows ~150–260 kg; neonates ~19 kg birth weights referenced in regional ecology notes.', diet: 'Concentrate grazer: short sweetveld, rhizomatous grasses; thornveld camps on MIWESU rotations.', }, 'golden-wildebeest': {
    heroImage: '/images/golden-wildebeest_card.png', rowlandWardMinimum: 'Same Rowland Ward width minima as blue wildebeest (colour morph)', averageTrophy: 'Horn benchmarks equal blue conspecifics, judge age via boss, mask darkness, herd role', recommendedCaliber: '.338 Win Mag · .300 Win Mag · .375 H&H (premium controlled expansion)', optimalSeason: 'Feb–Apr rut overlap · May–Oct crepuscular plains hunting', heroEyebrow: 'Golden morph · Same species, same ethics', sciMinimum: 'SCI treats as blue wildebeest phenotype, scoring identical; confirm trophy import paperwork with PH.', bulletConstruction: 'Match blue wildebeest guidance: bonded/monolithic .30+ class for confident penetration.', liveWeight: 'Mirrors blue wildebeest mass, colour genetics do not lighten bone or boss.', diet: 'Identical grazing ecology to blue wildebeest; manage as shared carrying capacity.', }, impala: {
    heroImage: '/images/impala_card.png', rowlandWardMinimum: 'Min. 23⅝″ horn length along curve (Rowland Ward)', averageTrophy: 'Sweetveld rams often 24–26″; Kalahari-edge genetics may push longer lyres', recommendedCaliber: '.243 Win · 6.5mm Creedmoor · .308 Win (accurate, flat-shooting loads)', optimalSeason: 'Apr–May rut · May–Oct dry fringe glassing', heroEyebrow: 'Athlete of the bushveld', sciMinimum: 'SCI impala categories combine horn lengths and circumferences, confirm minima for your award goal.', bulletConstruction:
      'Controlled-expansion 85–165 gr class matched to calibre; avoid varmint thin-jacket splash on scapula.', liveWeight: 'Rams ~40–76 kg; ewes ~30–53 kg depending on subpopulation nutrition.', diet: 'Mixed feeder: flush grass, Acacia pods, Combretum browse, Karoo shrubs seasonally.', }, 'dapple-impala': {
    heroImage: '/images/dapple-impala_card.png', rowlandWardMinimum: 'Min. 23⅝″ horn length (identical to common impala)', averageTrophy: 'Coat variant only, select on horn / age, not dapple alone', recommendedCaliber: '.243 Win · 6.5mm Creedmoor · .308 Win', optimalSeason: 'Apr–May rut · May–Oct stalking windows', heroEyebrow: 'SCI colour record · Same biology', sciMinimum: 'SCI classifies under impala / colour-variant policy, verify measurers’ notes for current season.', bulletConstruction: 'Identical to impala: tough deer-class bullets, not explosive small-game pills.', liveWeight: 'Same mass envelopes as nominate impala.', diet: 'Identical mixed-feeding strategy, quota ties to shared impala census.', }, gemsbok: {
    heroImage: '/images/gemsbok_card.png', rowlandWardMinimum: 'Min. 40″ long horn (Rowland Ward longest-horn philosophy); confirm drying rules', averageTrophy: 'Desert-edge bulls 42–45″+ cited in regional guides; cows may out-length bulls, judge sex on neck, bases, behaviour', recommendedCaliber: '.300 Win Mag · .300 WSM · .338 Win Mag · .375 H&H', optimalSeason: 'May–Aug cooler stalk intervals · dawn/dusk glassing', heroEyebrow: 'Oryx · Dermal shield · Open scrub', sciMinimum:
      'SCI gemsbok scoring emphasises length + base circumferences, gold-class references near 40″+ in many reference hunts; verify book year.', bulletConstruction:
      'Monolithic copper or bonded heavyweights mandatory, “deer softpoints” splash on shield bone; weight-retention beats speed alone.', liveWeight: 'Bulls ~230–250 kg field norms; cows ~200–210 kg; exceptional farm bulls heavier.', diet: 'Graze/browse plus succulents, tubers, melons; facultative drinker with desert renal strategy.', }, warthog: {
    heroImage: '/images/warthog_card.png', rowlandWardMinimum: 'Min. 13″ tusk length per Rowland Ward tusk measurement protocol', averageTrophy: 'Mature boars with heavy cutters and stained ivory; judge age via warts, snout thickness, solo behaviour', recommendedCaliber: '7×57 · .308 Win · .30-06 (180-class controlled expansion)', optimalSeason: 'Jun–Oct dry concentration at water · cooler morning emergence', heroEyebrow: 'Opportunity boar · Razor lowers', sciMinimum: 'SCI warthog categories use tusk + length criteria, confirm drying and export nuances with PH.', bulletConstruction:
      'Medium game bullets with bonded shank or all-copper; shot angles often present brushed hair and cartilage shielding.', liveWeight: 'Boars often ~60–100+ kg; large individuals to ~150 kg referenced; sows lighter in sounders.', diet: 'Rooting omnivore: rhizomes, tubers, short grass, occasional opportunistic protein; water-dependent behaviour near pans.', }, blesbok: {
    heroImage: '/images/blesbok_card.png', rowlandWardMinimum: 'Min. 16½″ horn length (Rowland Ward)', averageTrophy: 'Typical trophy rams 17–19″ on high-plane sweetveld; basal mass matters', recommendedCaliber: '.270 Win · .308 Win (140–165 gr controlled expansion)', optimalSeason: 'Mar–May rut · year-round on managed veld', heroEyebrow: 'Highveld blaze · Ringed lyre', sciMinimum: 'SCI blesbok / bontebok-type scoring, verify current chart for your award tier.', bulletConstruction: 'Standard plains-game bonded or partition; pass light varmint loads.', liveWeight: 'Rams ~65–80 kg; ewes ~55–70 kg; shoulder height ~84–100 cm.', diet: 'Sweetveld grazer with flush preference; uses burnt regrowth and short chlorophyll picks.', }, bushbuck: {
    heroImage: '/images/bushbuck_card.png', rowlandWardMinimum: 'Min. 15″ horn length (Rowland Ward)', averageTrophy: 'Serious rams 14–16″ field class; broomed tips may shorten tape while mass impresses', recommendedCaliber: '.308 Win · .30-06 · 9.3×62', optimalSeason: 'May–Sep dry river lines · ethical twilight still-hunts', heroEyebrow: 'Riverine · Spiral daggers', sciMinimum: 'SCI combined-score entry (~31″ bronze class referenced in bushbuck manuals, confirm with measurer).', bulletConstruction: 'Short-range clarity: bonded / all-copper; expect tight lanes and exit concerns.', liveWeight: 'Rams ~40–80 kg habitat-dependent; ewes lighter; thicket nutrition swings mass.', diet: 'Browser of riverine fringe, forbs, fruit; raided crops on disturbed boundaries, ethics sensitive.', }, 'cape-buffalo': {
    heroImage: '/images/cape-buffalo_card.png', rowlandWardMinimum: 'Min. 40″ tip-to-tip spread (Rowland Ward dangerous-game benchmarks)', averageTrophy: 'Hard-bossed bulls with worn bosses / bird-scar narratives; judge age before inches', recommendedCaliber: '.375 H&H (legal SA DG minimum) · .416 Rigby · .458 Lott (PH-directed)', optimalSeason: 'Jun–Oct dry herd compression · professional dangerous-game protocols', heroEyebrow: 'Dangerous game · Fused boss', sciMinimum: 'SCI buffalo scoring integrates spread, widths, engage official measurer; CITES paperwork parallel track.', bulletConstruction:
      'DG solids or heavy controlled-expansion by PH plan, no match tips, no “plains game experiments.”', liveWeight: 'Bulls ~500–900 kg referenced; cows ~300–700 kg; true mass stuns unprepared shooters.', diet: 'Obligate bulk grazer, grass and sedge dominance even in thicket estates; water-coupled movements.', }, lechwe: {
    heroImage: '/images/Lechwe_card.png', rowlandWardMinimum: 'Min. 26″ longest horn (Rowland Ward red lechwe qualification, confirm drying period)', averageTrophy: 'Gold-class references often 26–30″+ class in hunting literature; ring mass elevates score', recommendedCaliber: '.270 Win · .308 Win · .300 Win Mag (quality bullets)', optimalSeason: 'May–Sep cooler stalks near wetland margins', heroEyebrow: 'Red lechwe · Water-edge specialist', sciMinimum:
      'SCI Method 7 (uncurved horn procedures), sums lengths + base circumferences; drying rules apply for record entry.', bulletConstruction: 'Controlled-expansion suitable for medium antelope; respect fluid hits near water.', liveWeight: 'Rams ~90–128 kg cited; ewes ~50–80 kg, environment swings condition.', diet: 'Semi-aquatic grazer: floodplain grasses, sweet shoots; pan-driven movements.', }, 'livingstone-eland': {
    heroImage: '/images/livingstone-eland_card.png', rowlandWardMinimum: 'Min. 30″ horn length (regional Rowland Ward plains-game tables)', averageTrophy: 'Bulls exceed 30″ spirals; literature cites world-class 44–46″ Livingstone references', recommendedCaliber: '.338 Win Mag · .375 H&H · 9.3×62 Mauser', optimalSeason: 'Apr–Jun activity pulse · May–Oct open veld evaluation', heroEyebrow: 'Giant spiral · Browser-grazer', sciMinimum: 'SCI eland categories aggregate horn lengths + circumferences, confirm award thresholds.', bulletConstruction:
      'Eland punish lightweight bullets: monolithic, thick Partition-class, heavy .338/.375 preferred.', liveWeight: 'Bulls ~400–1,000+ kg cited; cows ~300–600 kg; metabolic giants.', diet: 'High-browser with grass flush: Acacia pods, broken canopies, sweetveld grasses post-rain.', }, 'red-hartebeest': {
    heroImage: '/images/red-hartebeest_card.png', rowlandWardMinimum: 'Min. 23″ longest horn (Rowland Ward, verify measurer interpretation)', averageTrophy: 'Mature bulls show heavy basal rings and heart-shaped anterior horn silhouette; SCI composite commonly 62″+ for book-class discussions', recommendedCaliber: '.30-06 Springfield · .300 Win Mag · .338 Win Mag', optimalSeason: 'May–Sep dry open plains · fire-flush attraction', heroEyebrow: 'Heart-beast horns · Selective grazer', sciMinimum: 'SCI scoring sums both horn lengths + circumferences, minima near 62″ referenced in regional trophy literature.', bulletConstruction: 'Bonded .30-cal 165–180 gr baseline; monolithics welcome on old bulls with thick pedicle bases.', liveWeight: 'Bulls ~150–200 kg; cows ~120 kg baseline, nutrition shifts totals', diet: 'Selective grazer on medium sward height; loves green-flush and seed heads; mopane shade geometry.', }, springbok: {
    heroImage: '/images/springbok_card.png', rowlandWardMinimum: 'Min. 14″ horn length (Rowland Ward springbok entry)', averageTrophy: 'Common rams ~12–14″; Kalahari genetics frequently stretch toward mid-teens+', recommendedCaliber: '.243 Win · 6.5mm Creedmoor · .270 Win (high-BC, wind-resistant)', optimalSeason: 'Sep–Nov rut pulse · year-round Karoo-style stalking', heroEyebrow: 'National emblem · Pronking signal', sciMinimum: 'SCI springbok / variant categories, confirm colour-variant scoring if hunting copper/black/white slam components.', bulletConstruction:
      'Accurate medium-game bullets with BC suited to 300 m ethical shots; wind buckles light pills on pans.', liveWeight: 'Rams ~33–48 kg; ewes ~27–38 kg; Kalahari forms can exceed these averages.', diet: 'Intermediate feeder: Karoo shrubs, succulents, grass flush; water-independent physiology with dew / melon strategy.', },
} satisfies Record<SpeciesSlug, SpeciesHuntingSpecs>
