import type { SpeciesPowerDeepDive, SpeciesSlug } from '@/lib/species-power-types'

/**
 * Long-form editorial distilled from MIWESU animal_knowledge research briefs.
 * Three H2-aligned blocks per species: ecology, sign/tracking, ethical shot placement.
 */
export const SPECIES_POWER_DEEP_DIVE: Record<SpeciesSlug, SpeciesPowerDeepDive> = {
  'greater-kudu': {
    ecologyAndBehavior: `The Greater Kudu is a thicket and savanna-woodland specialist, an edge species that prospers where sweetveld browse, acacia thickets, and broken canopy create cover and ladder-fed forage. Bulls routinely shoulder 140–160 cm at the withers and carry 190–270 kg of muscle behind horns that complete two and a half to three open spirals; cows are hornless, lighter, and operate in maternal herds where large “radar” ears and disruptive flank stripes break the outline in dappled shade.

Kudu browse deliberately: narrow muzzle, mobile lips, and a catalogue of woody plants (Vachellia/Senegalia, Combretum, sickle bush, seasonal pods and fruit) define their diet. A fascinating field reality is tannin “chemical warfare”, acacias spike astringency within minutes of leaf damage and signal neighbours with ethylene; kudu respond by feeding briefly and moving upwind, spreading utilisation and protecting rumen function.

Activity is crepuscular. In heat they ghost into the deepest shade; under pressure they may become almost nocturnal. Rut peaks April–June, necks swell, bulls wrestle with interlocked spirals (with rare “death lock” tragedies documented), and the deep bark alarm rolls hundreds of metres. Calves are hiders: cryptic, scent-minimising, and dependent on summer cover. On foot, expect freeze-and-assess before flight; the “look back” pose aligns horn with branches and frustrates rangefinding.`, trackingAndSpoor: `Kudu spoor is elongated-narrow compared with the rounder, heart-like impression of blue wildebeest. Mature bull tracks may approach ~9 cm length × ~6 cm width in soft substrates, with blunt toe tips and heavier heel load from chest and neck mass; cows are smaller and sharper. Walking gait often registers direct register or slight overstep; at speed the hoof splays and dewclaws may mark in sand.

Dung is typical small-antelope pellets when fibre is dry; near water or lush forage piles loosen. Trails lead between browse tiers and drink sites, kudu rarely dry-season more than a few kilometres from dependable water unless succulents (e.g., tsamma, Portulacaria) bridge the gap. In the Makoppa mosaic, look for parallel rubs on horizontal limbs, polished horning on saplings, and the quiet “nursery” loops of ewe groups versus the lone circuits of old bulls in broken topography.`, ethicalShotPlacement: `Treat the kudu as a large tragelaphine, not a temperate deer: the heart sits low and forward between the forelegs, the “African low” rule applies. On true broadside, follow the back of the front leg and intersect the lower third of the body for heart–lung convergence; “behind the shoulder” North American shorthand alone often wastes shot potential into liver or paunch if angle varies a degree.

Quartering-away is devastating when you anchor through off-shoulder exit, drive heavy bonded or partition-style bullets from substantial .30-class or 7mm magnums through the thorax. Face-on “teacup” shots to the chest are for professionals only, the target is minute and flanked by massive bone. Twigs matter: match premium controlled-expansion or monolithic projectiles to your calibre and verify zero at realistic bushveld distances. Recover every Grey Ghost as diligently as you glassed it, wounded kudu use thicket like armour.`, }, wildebeest: {
    ecologyAndBehavior: `Blue wildebeest are concentrate grazers built for short, sweet grass and high visibility on the plains edge. Bulls commonly mass ~250–290 kg with a humped forehand, charcoal boss, and jet-black facial mat; cows are lighter (~150–260 kg) and show the chestnut forehead “fireplace” between slenderer horns. Neonates wear camouflage tawny coats and sync with seasonal pulses on the veld.

Socially, nursery and breeding herds interweave with bachelor groups; territorial bulls fence with soil-horning, flank strutting, and violent boss clashes. Predators (lion, hyena, wild dog) shape flee behaviour, herds stampede with explosive acceleration, then reassess. In Limpopo’s iron-rich Hutton soils, expect rust-stained hooves and horn striations. Dry-season concentrates animals on water and mineral licks; rut generally Feb–Apr with heightened aggression and movement. Golden and other colour phases are the same species under recessive genetics prized on well-managed Waterberg farms, ethics and shot protocol remain unchanged.`, trackingAndSpoor: `Tracks are blunt, rounded, and “ hearted” front hooves carrying huge body mass; dewclaws register in mud. Stride length and depth differentiate lumbering herd walks from explosive flight. Dung varies from firm pads on green flush to fibrous cakes on standing hay.

Rubs on leadwood and mopane, wallows near seeps, and manicured pathways to water define circuit maps. Because wildebeest read wind and horizon flicker acutely, stalks demand use of dongas, termitaria, and sun angle, glass for sentinel cows watching perpendicular to the herd’s feed axis.`, ethicalShotPlacement: `The thorax rides under a deceptive shoulder hump, many shooters impact high through the dorsal “void.” Pick the lower third intersection on broadside, tight on foreleg; the heart–lung field rewards a bullet that penetrates scapula if needed. Quartering-away: exit off-side shoulder; avoid raking only paunch on steep angles.

Use .300-class bonded bullets minimum in general practice; open bulls justify .338 or 9.3 mm when brush deflection risk is real, and .375 remains a professional favourite when herds are nervous and distances collapse fast. Bow shots demand tight blinds and impeccable range discipline.`, }, 'golden-wildebeest': {
    ecologyAndBehavior: `Golden wildebeest are colour-morph blue wildebeest (Connochaetes taurinus), not a hybrid with black wildebeest. Genetics concentrate palomino–golden pelage while anatomy, boss morphology, rut timing, and grazing ecology mirror conspecifics. Expect identical mass ranges, maternal herd structures, and predator response.

On private Waterberg veld they are managed as premium trophies: line breeding intensifies coat expression but demands vigilance on founder diversity and inbreeding depression. Hunters should evaluate horn boss, spread curve, and body conformation exactly as for blue bulls, colour alone never substitutes for age-class judgement or sustainability.`, trackingAndSpoor: `Sign mirrors blue wildebeest, review the blue species entry for spoor, dung, and herd movement cues. Bright pelage can flash in low sun; plan stalks when contrast drops (cloud, oblique light) and exploit terrain masks relentlessly.`, ethicalShotPlacement: `Apply identical shot geometry and bullet selection as for blue wildebeest, low heart–lung line, cautious of hump illusion, bonded or monolithic projectiles, and disciplined follow-through when herds string out across red dirt pans.`, }, impala: {
    ecologyAndBehavior: `Impala epitomise the mixed-feeding athlete: 40–76 kg rams carry lyrate annulated horns up to ~92 cm; ewes are hornless and lighter. They exploit sweetveld mosaics, Vachellia, Combretum, mopane understorey, and flush grasses, switching browse and graze with rainfall. Deep vibrissae rooted in sinus beds map thorn tunnels at night; explosive alarm barks sync herd flight.

Rams hold leks and turf boundaries autumn into winter; combat is ritualised clashing on knees with horn hooks. Calves “lie out” in cover while mothers feed; predation pressure from wild dog, leopard, and cat guild keeps herds rotating through ecotones. Waterberg farms with impala at carrying capacity show elegant condition curves after spring flush and lean winter honesty, quota conversation must follow census, not ego.`, trackingAndSpoor: `Tracks show sharp cloven symmetry, front marginally larger under horn/neck weight. Droppings are small uniform pellets in strings when browsing; greener feed softens form. Game paths braid between pans, termite sentinels, and mineral latrines.

Because impala parse movement instantly, successful trackers freeze when sentinels lift chins, peripheral herd members reveal intent before the trophy ram.`, ethicalShotPlacement: `The chest is compact; heart–lung sits low and slightly forward, pin the foreleg-hairline intersection in the lower third. Quartering-away: thread to off shoulder; quartering-to: refuse unless highly skilled, scapula and brisket forgiving windows are narrow.

.243 through .308 with quality 160-class .30 cal bullets anchor rams; light cup-and-core at high velocity can explode on bone. Ranges stretch on open pans, verify drops and wind, especially on 250 m+ ethical shots.`, }, 'dapple-impala': {
    ecologyAndBehavior: `Dapple impala are Aepyceros melampus carrying recessive pelage genes that mottle roan–grey patches across the classic fawn canvas. Horn growth, rut violence, diet breadth, and predator interplay are unchanged from nominate impala, they remain mixed feeders of bushveld fringe and sweetveld lawns.

On MIWESU the morph is stewarded as a genetic asset: harvest focuses on surplus males and post-census authorization, never on colour novelty alone. International hunters should expect identical cartridge and optics standards, the quarry is not “easier” because it is rare; often it is warier after selective pressure.`, trackingAndSpoor: `Spoor, dung, and trail signatures match common impala, use the impala tracking notes. Where colour contrasts with iron-red soil, consider stalk geometry at dawn/dusk to reduce specular flash off pale patches.`, ethicalShotPlacement: `Use the identical vital triangle and ammunition guidance as for common impala, low heart–lung broadside, bonded or tough cup construction, and no marginal neck or head “experiments” for the sake of hide preservation.`, }, gemsbok: {
    ecologyAndBehavior: `Gemsbok are hippotragine heavyweights adapted to arid and semi-arid scrub, straight lances of horns, bold facial masks for disruptive camouflage, and a dermal shield that thickens the shoulder line against stabs from rivals (and complicates bullet delivery). Bulls often span 230–250 kg (exceptional farm bulls heavier); cows are slightly lighter but may grow longer horns, SCI scoring can favour length-dominant females.

They are facultative drinkers but can persist on metabolic water from melons, tubers, and succulents; kidneys concentrate filtrate aggressively. The carotid rete permits selective brain cooling when core temperature spikes, behavioural heat load is extreme midday. Herds mix breeding groups with territorial displays: broadside dominance posturing escalates to fencing combats that can impale lions in documented defences.

On Waterberg scrub transitions gemsbok behave like open-country athletes, eyesight is exceptional; stalks are chess, not sprints.`, trackingAndSpoor: `Hooves print broad ~10–12 cm heart-rounded tracks in sand; dewclaws register in yielding substrates. Droppings are oval pellets ~1.5–2 cm dry-season, clumping greener flushes. Excavations for bulbs and sign-post scrapes punctuate dry pans.

Long straight horn casts misleading shadows at last light, glass for symmetrical bases and bull neck mass versus cow elegance before committing kilometres in soft sand.`, ethicalShotPlacement: `The shoulder “hump” tricks elevation, hold low on broadside: foreleg line, lowest third, heart clustered between legs. Quartering-away demands a bullet that will cross paunch and still reach far lung, monolithic solids or bonded heavyweights from .300 Win Mag class upward are standard professionalism. Avoid soft deer bullets on the shield; they splash or pin superficially.

Quartering-to and tight frontal angles are high-risk, respect the animal’s reputation for reflex strikes after apparent collapse.`, }, warthog: {
    ecologyAndBehavior: `The common warthog is a suline oddity: elevated prenasal disc for rooting, ever-growing upper “pushing” tusks and honed lower blades, and sebaceous “warts” that cushion boar combat. Boars may exceed 100 kg with trophy tusks commonly referenced 25+ cm outside curves on mature animals; sounder sows organise daycare while boars wander solitarily between rut.

They kneel to graze short swathes, erupt from aardvark burrows hind-first when threatened, and sun like armour-plated anomalies at wallows. Diet: rhizomes, bulbs, short grasses, carrion opportunism, and agricultural edges where fences fail ethics review. Predators respect the slash, wild dog hunts turn messy when a boar anchors in a hole.

MIWESU treats warthog as opportunity quarry in quota balance, still demand age class respect and rapid field processing in heat.`, trackingAndSpoor: `Tracks show squared depth from kneeling habits; dewclaws often register. Wallows, rooted belts, and tufts of hair on burrow lips flag usage. Dung is classic suid meanders or heaps near latrines.

Sounders loop predictable morning feed arcs; lone boars cruise thicker cover, track only with PH guidance once blood is drawn because reversals into scrub are notorious.`, ethicalShotPlacement: `Preferred broadside: low behind shoulder into heart–lung, the chest is compact and partially shielded by cartilage. Avoid high spine-only fantasies; frontal “stern shots” are PH-domain geometry. Heavy-for-calibre soft points or all-coppers from .308/7×57/.30-06 classes perform reliably; adjust downward for flank shots to avoid paunch only wounds.

Every tusk animal deserves follow-up readiness, lowered vitals behind bone can still sprint to holes.`, }, blesbok: {
    ecologyAndBehavior: `Blesbok are medium Damaliscus pygargus phillipsi grassland antelope, 65–80 kg rams, 55–70 kg ewes, branded by the forward white blaze bisected by the brown nasal band (field-separate from bontebok by blaze continuity rules). Both sexes carry heavily annulated lyre horns with sharp tips; rams show basal mass and sun-bleached straws.

They formed super-herds historically; modern fragments retain synchronised lying postures midday (heads low, sun behind) and short-line flight from cover to cover. Rut violence includes kneeling stabs toward flanks, respect horn reach in blinds. Diet centres chlorophyll-rich sweetveld, green flags after burn, and cultivated margins where management allows.

On red Limpopo soils they’re visible at distance, plan approaches on contours, not skyline skylarking.`, trackingAndSpoor: `Cloven prints are neat on hardpan, deeper on vlei edges; trotting strings run ruler-straight when fleeing to known holes in fence lines. Dung piles (middens) signal dominant rams, lie-over stains mark ritual ground.

Pair spoor with crop selection and dew, morning gloss on grass reveals night grazing circuits valuable for ambush planning with PH oversight.`, ethicalShotPlacement: `Chest sits lower than the steep shoulder line suggests, hold mid-to-low on broadside behind foreleg;.270/.308 with quality cup or bonded bullets anchor rams; avoid hollow-point varmint fragility. Quartering-away: exit forward of off shoulder; steep quartering-to: pass, scapula deflection ruins days.

Because groups stampede in formation, identify your ram twice, blaze photography can flare in optic bloom.`, }, bushbuck: {
    ecologyAndBehavior: `Bushbuck (Tragelaphus sylvaticus around MIWESU) shrink the kudu playbook into riverine and thicket packets, adult rams may reach 40–80 kg depending on nutrition, with red–chocolate pelage darkening as testosterone cements status. Only rams carry spiral-keeled daggers that grow parallel to the neck for tunnel running.

They are crepuscular and notoriously human-nocturnal near disturbance, lawn raids at midnight are common high-protein farm realities. Rut behaviour skews violently territorial; river loops become gantlets of musk-heavy dung and hook-scars on bark.

Wounded bushbuck myth is not myth, they counter-ambush trackers and drive horn low. Never escalate pursuit without PH sequencing.`, trackingAndSpoor: `Spoor is petite, pointed, often solitary alongside drag-marks where dew has slicked clay. Pellets resemble miniature kudu browse signatures but cluster near browse paw-down sites. Hair snags on Buffalo thorn and wait-a-bit tell fresher stories than prints alone.

Rain lifts daytime movement odds, still-hunts along seep lines outperform marching through midday mopane bake.`, ethicalShotPlacement: `Tight quarters amplify error: pick lanes before the shot; low lung behind shoulder on broadside; avoid steep upward angles that skate spine. Tough .30-cal bullets or 9.3 mm for quartering solutions through paunch; never skull or “neck fluff” lottery on a species famous for retribution.

Bowhunters need perfect lateral clearance, twig ricochet is unforgiving at 18 m “easy” shots.`, }, 'cape-buffalo': {
    ecologyAndBehavior: `Syncerus caffer caffer is the southern savanna buffalo, herd matriarchs orchestrate democratic standing votes on direction; bulls segregate into bachelor files before the hardened “dagga boy” loner phase. Mass spans ~500–900 kg for dominant bulls with fused horn bosses by ~8–9 years; cows lack fusion and carry redder, sleeker frames.

They are obligate bulk grazers, not browse-switchers in modern Addo-class studies, cycling massive grassy mouthfuls and ruminating through heat. Mud armour cools and smothers ectoparasites; oxpeckers scream half-truths between tick cleans and wound-lip blood.

Danger is statistical and individual, charge to 50 km/h, soak non-CNS hits, and circle back downwind on wounded packs. This is professional-hunter country, clients train repetition until muscle memory overtakes excitement.`, trackingAndSpoor: `Spoor resembles heavy cattle, ~13–14 cm fronts excluding dewclaws, rounded outer walls, full-register walks in mud strings. Fronts dwarf hinds; mud flings to wither height narrate wallows. Dung is voluminous cakes studded with fibre grades.

Trackers integrate audio (grunts), broken grass holograms, and rufescent calf guard clusters, never silo spoor without wind cone mapping.`, ethicalShotPlacement: `DG minimum in South Africa remains .375 H&H class, many PH’s prefer .416 Rigby or .458 Lott for stop-control psychology, not just energy tables. Broadside: drive through heart/lung tight behind leg; do NOT Pop high “lung only” fantasies on quartering-to giants.

Classic “Texas heart shot” frontal and spinal probes are PH-level choices demanding precise visualization of elevated cardiac access. Follow-up protocols, shooting sticks, and quartering angles are rehearsed before contact, wounded buffalo are curriculum, not anecdotes.`, }, lechwe: {
    ecologyAndBehavior: `Red lechwe (Kobus leche) specialise in floodplain sweet grass and shallow edge habitats, harem herds, aquatic escape reflexes, and horn mass biased to rams (~90–128 kg benchmarks in literature; females lighter). Rut features parallel horn fencing in shallow water and spectacular lateral displays.

They are water-coupled psychologically even when pans shrink, expect nervous resets when drought concentrates competition. On highveld-edge farms introducing lechwe, carrying capacity ties to pan reliability and fencing that respects their river aesthetic MIWESU honours census before quota uplift.`, trackingAndSpoor: `Tracks appear cloven, often sheared-edge from soft silt; splash talus and belly-slide marks betray panic exits into water. Dung pellets parallel impala family sizes but cluster at sodden latrines.

Glass horn rings from elevation, water glare eats midday contrast; polarized optics repay investment.`, ethicalShotPlacement: `Broadside: tight behind shoulder in lower third, bodies are leaner than wildebeest but dense when wet. Quartering-away angle management avoids gut sliders into water where recovery dives become hazardous.

.270 and .308 with controlled expansion suffice at ethical plains ranges; pass marginal backlight shots that silhouette only horns.`, }, 'livingstone-eland': {
    ecologyAndBehavior: `Livingstone eland (Taurotragus oryx livingstonii) merge ox mass with spiral-horned nerves, bulls 400–1,000+ kg with cervicothoracic humps, females 300–600 kg, calves precocial after ~30–36 kg birth weights. Both sexes horn, but cow horns may exceed bull length while bulls carry basal mass for shoving matches.

They hook branches to collapse browse ladders Acacia pods matter dry-season; grass spikes green season, true dietary plasticity with ruminant pause rhythms. Eland bolt as explosively as their mass mocks physics, reserve energy in stalks.

On MIWESU they anchor biomass perception, harvest decisions ride census, age-class horn rollover, and cold-room capacity.`, trackingAndSpoor: `Tracks are massive hearts that splay in silt, dewclaws flag in mud like dinner plates underscoring half-ton load. Broken branches at browse heights impossible for smaller antelope, oval dung mounds, and musk threads in rut signpost corridors.

Follow with overlapping teams, lone trackers lose time underestimating stride length after alarm.`, ethicalShotPlacement: `Eland reward .338 Win Mag and .375 class bullets from structured shooting rests, scapula and thick skin laugh at light varmint pills. Broadside: classic lower-third rule behind leg; quartering-to heavily discouraged for clients.

Angled shots through paunch demand heavy monolithics or partitioned solids; expect long death runs if exit fails opposite lung.`, }, 'red-hartebeest': {
    ecologyAndBehavior: `Red hartebeest (Alcelaphus buselaphus caama) wear extreme shoulder-hump fulcrums and elongate skulls carrying heart-view horns from shared frontal pedicles. Bulls ~150–200 kg exceptional, cows ~120 kg; both sexes horn with masculine basal mass dominance.

Selective grazing on green-flag grasses and fire-follow flushes defines them; preorbital glands paste scent to horning posts. Combat is kneeling wrestle with hook-lock risk. Calves hide tawny absence of adult blackout masks until predation window narrows.

Savanna visibility is their MO, ethical approach = topography + patience + wind, not sprint swaps. MIWESU pairs them with sweetveld fire rotation understanding.`, trackingAndSpoor: `Hooves punch neat paired crescents accelerating to comma sweeps in flight; soil horning craters flank territorial loops. Dung stacks on domanial middens, wind-check before sitting blinds.

High shoulder optical illusion raises crosshairs, verify off sticks, not adrenal guesswork.`, ethicalShotPlacement: `Broadside again means low on body behind leg, thorax tucks under hump silhouette. SCI scoring emphasises composite horn totals; Rowland Ward lists minimum ~23″ on longest horn per sourced tables, verify measurer confirmation pre-hunt.

Use .30-06/.300 Win Mag minimum serious class with premium bonded; kudu-grade monolithics welcome on heavy old bulls.`, }, springbok: {
    ecologyAndBehavior: `Springbok are Antidorcas marsupialis, not gazelline congeners, sporting a dorsal “marsupial” fan of sebaceous white signalling that can flash pheromone-laden sweetness when erected. Rams ~33–48 kg (Kalahari forms heavier), horn lyres to ~50 cm; ewes slighter.

Pronking is honest handicap signalling to coursing predators, wasteful jumps prove fitness. Mixed feeding (Pentzia, Pteronia Karoo shrubs, flush grasses) underpins water independence via night dew, succulent moisture, and tight kidney economics. Colour variants (black, white, copper) remain one species under captive selection pressure, judge horn and age, not novelty.

Historically trekbok migrations rivalled fiction; modern fair-chase pursues wind, patience, and kilometre closes on open pans.`, trackingAndSpoor: `Tracks are sharp petite wedges, front barely larger; bounding gallop strings elongate. Dung pellets mass like impala signatures with scatter at pan lip mud.

Sentinel ewes lift chins before pronk waves, adjust tempo to freeze-frame discipline; crawling finals beat upright swagger every time.`, ethicalShotPlacement: `Vitals ~15–20 cm zone at 250 m+ demands confirmed DOPE, .243 through 6.5 Creedmoor excel with high-BC 95–140 gr pills; .270 Win classic. Wind buckles light bullets on pans; practice actual heat shimmer lines.

Avoid marginal Texas heart angles, body depth is shallow; quartering shots magnify paunch-only risk. Anchor them as seriously as any “small” trophy because lost springbok humiliate tracker hours.`, }, }

export function getSpeciesPowerDeepDive(slug: SpeciesSlug): SpeciesPowerDeepDive {
  return SPECIES_POWER_DEEP_DIVE[slug]
}
